// ⚠︎ AUTO-GENERIERT via scratchpad/gen_recipes.py — nicht von Hand editieren.
//   Rezept-Katalog (Spiegel des Backends) für den Offline-first-Betrieb.
import type { Dish } from './fitness';

export const PRESET_DISHES: Dish[] = [
  { id: "p-reiskocher-protein-oats", name: "Reiskocher Protein-Oats", category: "breakfast", prep_min: 12, kcal: 390, prot: 30, carb: 52, fat: 8, equipment: ["ricecooker"], icon: "🥣", image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["80g Haferflocken", "1 Scoop Proteinpulver", "250ml Milch", "1 Banane", "1 Prise Zimt"],
    steps: ["Haferflocken, Milch und eine Prise Zimt in den Reiskocher geben und kurz verrühren.", "Deckel schließen und auf 'Cook' stellen – ca. 8–10 Minuten bis die Oats cremig quellen.", "Reiskocher öffnen, das Proteinpulver erst jetzt unterrühren (sonst wird es klumpig).", "Banane in Scheiben schneiden und auf die Oats geben. Warm servieren."] },
  { id: "p-overnight-oats-beere", name: "Overnight Oats Beere", category: "breakfast", prep_min: 5, kcal: 360, prot: 24, carb: 48, fat: 9, equipment: ["none"], icon: "🫐", image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["60g Haferflocken", "150g Magerquark", "150ml Milch", "100g TK-Beeren", "1 TL Honig", "1 EL Chiasamen"],
    steps: ["Haferflocken, Chiasamen, Quark und Milch in einem Glas gründlich verrühren.", "Beeren und Honig unterheben, sodass sich die Farbe leicht violett färbt.", "Abgedeckt über Nacht in den Kühlschrank stellen – mindestens 6 Stunden.", "Am Morgen kurz umrühren, bei Bedarf einen Schuss Milch für die Konsistenz zugeben."] },
  { id: "p-protein-pancakes", name: "Protein-Pancakes", category: "breakfast", prep_min: 15, kcal: 410, prot: 35, carb: 40, fat: 10, equipment: ["stove"], icon: "🥞", image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Banane", "2 Eier", "1 Scoop Protein", "40g Haferflocken", "1 Prise Backpulver"],
    steps: ["Banane mit einer Gabel zerdrücken und mit den Eiern verquirlen.", "Haferflocken, Protein und Backpulver unterrühren, 2 Minuten quellen lassen.", "Beschichtete Pfanne bei mittlerer Hitze leicht einfetten.", "Pro Pancake 2 EL Teig einfüllen, ca. 2 Min. braten bis Blasen aufsteigen, wenden.", "Goldbraun fertigbacken und warm stapeln."] },
  { id: "p-airfryer-french-toast", name: "Airfryer French Toast", category: "breakfast", prep_min: 12, kcal: 380, prot: 20, carb: 44, fat: 12, equipment: ["airfryer"], icon: "🍞", image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Scheiben Vollkorntoast", "1 Ei", "80ml Milch", "1 Prise Zimt", "1 TL Ahornsirup"],
    steps: ["Ei, Milch und Zimt in einem tiefen Teller verquirlen.", "Toastscheiben beidseitig kurz in der Eimilch tränken.", "Airfryer auf 180 °C vorheizen und die Scheiben einlegen.", "6–8 Minuten backen, nach der Hälfte wenden, bis goldbraun.", "Mit Ahornsirup beträufelt servieren."] },
  { id: "p-magerquark-bowl", name: "Magerquark-Bowl", category: "breakfast", prep_min: 5, kcal: 320, prot: 40, carb: 30, fat: 4, equipment: ["none"], icon: "🥛", image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Magerquark", "100g Beeren", "20g Nüsse", "1 TL Honig", "3 EL Wasser"],
    steps: ["Magerquark mit etwas Wasser glattrühren, bis er cremig ist.", "In eine Schale geben und mit Beeren, Nüssen und Honig toppen.", "Sofort genießen – liefert 40 g Protein für einen starken Start."] },
  { id: "p-reiskocher-milchreis", name: "Reiskocher Milchreis", category: "breakfast", prep_min: 30, kcal: 420, prot: 14, carb: 72, fat: 7, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["100g Milchreis", "400ml Milch", "1 EL Zucker", "1 Prise Zimt", "1 TL Vanille"],
    steps: ["Milchreis, Milch, Zucker und Vanille in den Reiskocher geben.", "Auf 'Cook' stellen und gelegentlich umrühren, damit nichts ansetzt.", "Nach ca. 25 Minuten ist der Reis weich und cremig.", "Mit Zimt bestreuen und warm oder kalt servieren."] },
  { id: "p-shakshuka", name: "Shakshuka", category: "breakfast", prep_min: 20, kcal: 340, prot: 22, carb: 18, fat: 20, equipment: ["stove"], icon: "🍳", image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 Eier", "1 Dose Tomaten", "1 Zwiebel", "1 Paprika", "1 TL Paprikapulver", "Salz, Pfeffer"],
    steps: ["Zwiebel und Paprika würfeln, in einer Pfanne mit etwas Öl glasig anbraten.", "Tomaten und Gewürze zugeben, 8 Minuten einköcheln lassen.", "Mit einem Löffel Mulden formen und die Eier hineingleiten lassen.", "Zugedeckt 5–6 Minuten garen, bis das Eiweiß gestockt ist. Sofort servieren."] },
  { id: "p-chia-pudding-vanille", name: "Chia-Pudding Vanille", category: "breakfast", prep_min: 5, kcal: 300, prot: 16, carb: 30, fat: 12, equipment: ["none"], icon: "🍮", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 EL Chiasamen", "250ml Milch", "1 TL Vanille", "1 TL Honig", "100g Mango"],
    steps: ["Chiasamen, Milch, Vanille und Honig verrühren, 5 Minuten stehen lassen.", "Erneut kräftig umrühren, damit keine Klumpen entstehen.", "Mindestens 4 Stunden (oder über Nacht) kühl quellen lassen.", "Mit Mangowürfeln toppen und servieren."] },
  { id: "p-ruehrei-mit-skyr-toast", name: "Rührei mit Skyr-Toast", category: "breakfast", prep_min: 10, kcal: 370, prot: 34, carb: 26, fat: 14, equipment: ["stove"], icon: "🍳", image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 Eier", "1 Scheibe Vollkornbrot", "2 EL Skyr", "Schnittlauch", "Salz, Pfeffer"],
    steps: ["Eier mit Salz und Pfeffer verquirlen.", "In einer beschichteten Pfanne bei geringer Hitze langsam stocken lassen, dabei rühren.", "Vollkornbrot toasten und mit Skyr bestreichen.", "Rührei auf den Toast geben, mit Schnittlauch bestreuen."] },
  { id: "p-smoothie-bowl-gruen", name: "Smoothie-Bowl Grün", category: "breakfast", prep_min: 8, kcal: 330, prot: 20, carb: 46, fat: 6, equipment: ["none"], icon: "🥝", image: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Banane", "100g Spinat", "150ml Milch", "1 Scoop Vanille-Protein", "Granola zum Toppen"],
    steps: ["Banane, Spinat, Milch und Protein cremig mixen – möglichst dickflüssig.", "In eine Schale gießen; sie sollte löffelbar sein, nicht trinkbar.", "Mit Granola und Bananenscheiben dekorativ toppen.", "Sofort löffeln, solange die Bowl kühl ist."] },
  { id: "p-airfryer-granola", name: "Airfryer Granola", category: "breakfast", prep_min: 18, kcal: 450, prot: 12, carb: 56, fat: 18, equipment: ["airfryer"], icon: "🥜", image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g Haferflocken", "30g Nüsse", "2 EL Honig", "1 EL Kokosöl", "1 TL Zimt"],
    steps: ["Haferflocken und Nüsse mit geschmolzenem Kokosöl, Honig und Zimt vermengen.", "Airfryer auf 160 °C vorheizen und die Mischung in die Schublade geben.", "12–14 Minuten backen, alle 4 Minuten durchrühren, bis goldbraun.", "Vollständig auskühlen lassen – dabei wird das Granola knusprig. Luftdicht lagern."] },
  { id: "p-protein-porridge-apfel-zimt", name: "Protein-Porridge Apfel-Zimt", category: "breakfast", prep_min: 12, kcal: 400, prot: 28, carb: 54, fat: 9, equipment: ["stove"], icon: "🍎", image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["60g Haferflocken", "1 Scoop Protein", "1 Apfel", "300ml Milch", "1 TL Zimt"],
    steps: ["Haferflocken mit Milch aufkochen und bei kleiner Hitze 5 Minuten köcheln.", "Apfel klein würfeln und unterrühren, weitere 2 Minuten garen.", "Vom Herd nehmen und leicht abkühlen lassen, dann das Protein einrühren.", "Mit Zimt bestreuen und heiß servieren."] },
  { id: "p-cottage-cheese-toast", name: "Cottage-Cheese-Toast", category: "breakfast", prep_min: 6, kcal: 290, prot: 24, carb: 28, fat: 8, equipment: ["none"], icon: "🧀", image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Scheiben Vollkornbrot", "150g Hüttenkäse", "1 Tomate", "Basilikum", "Salz, Pfeffer"],
    steps: ["Vollkornbrot nach Belieben toasten.", "Hüttenkäse mit Salz und Pfeffer würzen und auf das Brot streichen.", "Mit Tomatenscheiben belegen und mit Basilikum garnieren."] },
  { id: "p-bananen-haferflocken-waffeln", name: "Bananen-Haferflocken-Waffeln", category: "breakfast", prep_min: 18, kcal: 420, prot: 26, carb: 48, fat: 12, equipment: ["stove"], icon: "🧇", image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Bananen", "2 Eier", "60g Haferflocken", "1 Scoop Protein", "1 TL Backpulver"],
    steps: ["Alle Zutaten zu einem glatten Teig mixen.", "Waffeleisen vorheizen und leicht einfetten.", "Teig portionsweise einfüllen und 4–5 Minuten goldbraun backen.", "Mit Beeren oder Skyr servieren."] },
  { id: "p-beeren-kokos-chia-jar", name: "Beeren-Kokos-Chia-Jar", category: "breakfast", prep_min: 5, kcal: 310, prot: 15, carb: 34, fat: 13, equipment: ["none"], icon: "🥥", image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 EL Chiasamen", "200ml Kokosmilch", "100g Himbeeren", "1 TL Ahornsirup", "Kokoschips"],
    steps: ["Chiasamen mit Kokosmilch und Ahornsirup verrühren.", "10 Minuten quellen lassen, dann nochmal umrühren.", "Über Nacht kühl stellen.", "Mit Himbeeren und Kokoschips schichten und servieren."] },
  { id: "p-ei-muffins-aus-dem-airfryer", name: "Ei-Muffins aus dem Airfryer", category: "breakfast", prep_min: 18, kcal: 260, prot: 26, carb: 6, fat: 15, equipment: ["airfryer"], icon: "🧁", image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["4 Eier", "50g Schinkenwürfel", "30g Käse", "1 Handvoll Spinat", "Salz, Pfeffer"],
    steps: ["Eier verquirlen, Schinken, Käse und gehackten Spinat unterrühren, würzen.", "Silikon-Muffinförmchen zur Hälfte mit der Masse füllen.", "Airfryer auf 170 °C vorheizen, Förmchen einsetzen.", "10–12 Minuten backen, bis die Muffins aufgehen und fest sind."] },
  { id: "p-skyr-beeren-parfait", name: "Skyr-Beeren-Parfait", category: "breakfast", prep_min: 6, kcal: 300, prot: 32, carb: 32, fat: 4, equipment: ["none"], icon: "🍨", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Skyr", "80g Granola", "100g Beeren", "1 TL Honig"],
    steps: ["Skyr mit Honig glattrühren.", "In einem Glas abwechselnd Skyr, Granola und Beeren schichten.", "Mit einer Beerenschicht abschließen und sofort servieren."] },
  { id: "p-tofu-scramble", name: "Tofu-Scramble", category: "breakfast", prep_min: 12, kcal: 280, prot: 24, carb: 12, fat: 16, equipment: ["stove"], icon: "🍳", image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g fester Tofu", "1 TL Kurkuma", "1/2 Zwiebel", "1 Handvoll Spinat", "Salz, Pfeffer"],
    steps: ["Tofu mit den Händen zerbröseln.", "Zwiebel würfeln und in etwas Öl anbraten.", "Tofu und Kurkuma zugeben, 5 Minuten braten, bis er goldgelb ist.", "Spinat unterheben, würzen und servieren."] },
  { id: "p-protein-kaiserschmarrn", name: "Protein-Kaiserschmarrn", category: "breakfast", prep_min: 18, kcal: 430, prot: 32, carb: 44, fat: 12, equipment: ["stove"], icon: "🥞", image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 Eier", "1 Scoop Protein", "40g Mehl", "150ml Milch", "1 EL Rosinen", "Puderzucker"],
    steps: ["Eier trennen, Eiweiß steif schlagen.", "Eigelb, Protein, Mehl und Milch zu einem Teig rühren, Eischnee unterheben.", "Teig mit Rosinen in eine gefettete Pfanne geben, anbacken, dann zerrupfen.", "Weiter braten bis goldbraun, mit Puderzucker bestäuben."] },
  { id: "p-reiskocher-congee-suess", name: "Reiskocher Congee süß", category: "breakfast", prep_min: 35, kcal: 350, prot: 12, carb: 66, fat: 5, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["80g Reis", "600ml Wasser", "1 Apfel", "1 TL Zimt", "1 EL Honig"],
    steps: ["Reis und Wasser in den Reiskocher geben, auf 'Cook' stellen.", "Nach 20 Minuten den geraspelten Apfel unterrühren.", "Weitere 10 Minuten garen, bis eine breiige Konsistenz entsteht.", "Mit Zimt und Honig süßen."] },
  { id: "p-avocado-ei-toast", name: "Avocado-Ei-Toast", category: "breakfast", prep_min: 8, kcal: 360, prot: 18, carb: 30, fat: 20, equipment: ["none"], icon: "🥑", image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Scheiben Vollkornbrot", "1/2 Avocado", "1 gekochtes Ei", "Chiliflocken", "Zitrone, Salz"],
    steps: ["Avocado mit Zitrone und Salz zerdrücken.", "Vollkornbrot toasten und mit der Avocadocreme bestreichen.", "Gekochtes Ei in Scheiben darauf verteilen, mit Chiliflocken bestreuen."] },
  { id: "p-airfryer-cordon-bleu", name: "Airfryer Cordon Bleu", category: "main", prep_min: 20, kcal: 480, prot: 34, carb: 22, fat: 26, equipment: ["airfryer"], icon: "🍗", image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Hähnchenschnitzel", "2 Scheiben Kochschinken", "2 Scheiben Käse", "Semmelbrösel", "1 Ei", "Salz, Pfeffer"],
    steps: ["Schnitzel flach klopfen, würzen, je 1 Scheibe Schinken und Käse einrollen.", "Mit Zahnstochern fixieren, in verquirltem Ei und dann in Semmelbröseln wenden.", "Airfryer auf 190 °C vorheizen und die Röllchen einlegen.", "14 Minuten backen, nach der Hälfte wenden, bis die Panade goldbraun ist.", "Kurz ruhen lassen, Zahnstocher entfernen und servieren."] },
  { id: "p-airfryer-lachs-brokkoli", name: "Airfryer Lachs & Brokkoli", category: "main", prep_min: 15, kcal: 420, prot: 38, carb: 12, fat: 24, equipment: ["airfryer"], icon: "🐟", image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["180g Lachsfilet", "150g Brokkoli", "1 EL Olivenöl", "1/2 Zitrone", "Salz, Pfeffer"],
    steps: ["Brokkoli in Röschen teilen und mit Öl, Salz und Pfeffer vermengen.", "Airfryer auf 190 °C vorheizen, Brokkoli 5 Minuten vorgaren.", "Lachs würzen, dazulegen und weitere 8 Minuten garen.", "Mit Zitrone beträufeln und servieren."] },
  { id: "p-airfryer-suesskartoffel-pommes", name: "Airfryer Süßkartoffel-Pommes", category: "main", prep_min: 18, kcal: 310, prot: 5, carb: 58, fat: 7, equipment: ["airfryer"], icon: "🍠", image: "https://images.unsplash.com/photo-1493770348161-369560ae357d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 große Süßkartoffel", "1 EL Olivenöl", "1 TL Paprikapulver", "Salz"],
    steps: ["Süßkartoffel schälen und in gleichmäßige Stifte schneiden.", "Mit Öl, Paprikapulver und Salz vermengen.", "Airfryer auf 200 °C vorheizen, Pommes in einer Lage einlegen.", "16 Minuten backen, zweimal schütteln, bis sie knusprig sind."] },
  { id: "p-reiskocher-jollof-rice", name: "Reiskocher Jollof Rice", category: "main", prep_min: 30, kcal: 520, prot: 22, carb: 78, fat: 12, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Reis", "1 Dose Tomaten", "1 Zwiebel", "150g Hähnchen", "1 TL Paprika", "Gewürze"],
    steps: ["Zwiebel und Hähnchen würfeln.", "Alles mit Reis, Tomaten und Gewürzen in den Reiskocher geben.", "300ml Wasser zufügen und auf 'Cook' stellen.", "Nach 25 Minuten quellen lassen, auflockern und servieren."] },
  { id: "p-reiskocher-haehnchen-congee", name: "Reiskocher Hähnchen-Congee", category: "main", prep_min: 35, kcal: 360, prot: 28, carb: 46, fat: 6, equipment: ["ricecooker"], icon: "🍲", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["100g Reis", "150g Hähnchen", "1L Brühe", "1 Stück Ingwer", "Frühlingszwiebel"],
    steps: ["Reis, Hähnchen, Ingwer und Brühe in den Reiskocher geben.", "Auf 'Cook' stellen und 30 Minuten garen, bis der Reis zerfällt.", "Hähnchen herausnehmen, zerzupfen und zurückgeben.", "Mit Frühlingszwiebeln bestreuen und heiß servieren."] },
  { id: "p-airfryer-haehnchen-spiesse", name: "Airfryer Hähnchen-Spieße", category: "main", prep_min: 18, kcal: 350, prot: 42, carb: 8, fat: 14, equipment: ["airfryer"], icon: "🍢", image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g Hähnchenbrust", "2 EL Joghurt", "1 TL Curry", "1 Knoblauchzehe", "Salz"],
    steps: ["Hähnchen würfeln und mit Joghurt, Curry, Knoblauch und Salz marinieren.", "20 Minuten ziehen lassen, dann auf Spieße stecken.", "Airfryer auf 200 °C vorheizen und Spieße einlegen.", "12 Minuten garen, nach der Hälfte wenden."] },
  { id: "p-reiskocher-bibimbap", name: "Reiskocher Bibimbap", category: "main", prep_min: 30, kcal: 540, prot: 28, carb: 70, fat: 16, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Reis", "1 Ei", "150g Rindfleisch", "Karotte, Spinat, Gurke", "2 EL Gochujang", "Sesamöl"],
    steps: ["Reis im Reiskocher garen.", "Gemüse in Streifen schneiden, Rindfleisch in Sesamöl anbraten.", "Reis in eine Schale geben, Gemüse und Fleisch fächerförmig anrichten.", "Spiegelei daraufsetzen, mit Gochujang würzen und mischen."] },
  { id: "p-airfryer-falafel", name: "Airfryer Falafel", category: "main", prep_min: 22, kcal: 380, prot: 18, carb: 44, fat: 14, equipment: ["airfryer"], icon: "🧆", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Dose Kichererbsen", "1 Zwiebel", "2 Knoblauchzehen", "Petersilie", "1 TL Kreuzkümmel", "2 EL Mehl"],
    steps: ["Kichererbsen abtropfen und mit Zwiebel, Knoblauch und Gewürzen fein pürieren.", "Mehl unterkneten, bis eine formbare Masse entsteht.", "Kleine Bällchen formen und mit etwas Öl bepinseln.", "Airfryer auf 190 °C, 14 Minuten backen, nach der Hälfte wenden."] },
  { id: "p-rindfleisch-stir-fry", name: "Rindfleisch-Stir-Fry", category: "main", prep_min: 18, kcal: 460, prot: 38, carb: 30, fat: 20, equipment: ["stove"], icon: "🥩", image: "https://images.unsplash.com/photo-1550317138-10000687a72b?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Rindfleisch", "1 Paprika", "1 Zucchini", "2 EL Sojasauce", "1 Stück Ingwer", "1 EL Öl"],
    steps: ["Rindfleisch in feine Streifen schneiden.", "Wok stark erhitzen, Fleisch scharf 2 Minuten anbraten, herausnehmen.", "Gemüse mit Ingwer 3 Minuten braten.", "Fleisch zurückgeben, mit Sojasauce ablöschen und servieren."] },
  { id: "p-reiskocher-risotto", name: "Reiskocher Risotto", category: "main", prep_min: 30, kcal: 480, prot: 16, carb: 66, fat: 16, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Risottoreis", "600ml Brühe", "1 Zwiebel", "50g Parmesan", "100g Pilze", "1 EL Butter"],
    steps: ["Zwiebel und Pilze würfeln und mit dem Reis in den Reiskocher geben.", "Brühe zufügen und auf 'Cook' stellen.", "Nach 20 Minuten Butter und Parmesan unterrühren.", "Cremig rühren und sofort servieren."] },
  { id: "p-airfryer-haehnchenkeulen", name: "Airfryer Hähnchenkeulen", category: "main", prep_min: 30, kcal: 440, prot: 40, carb: 4, fat: 28, equipment: ["airfryer"], icon: "🍗", image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["4 Hähnchenkeulen", "1 EL Öl", "1 TL Paprika", "1 TL Knoblauchpulver", "Salz, Pfeffer"],
    steps: ["Keulen trocken tupfen und mit Öl und Gewürzen einreiben.", "Airfryer auf 190 °C vorheizen.", "25 Minuten garen, nach 15 Minuten wenden.", "Kurz ruhen lassen, damit sie saftig bleiben."] },
  { id: "p-vollkorn-pasta-bolognese", name: "Vollkorn-Pasta Bolognese", category: "main", prep_min: 25, kcal: 560, prot: 34, carb: 68, fat: 16, equipment: ["stove"], icon: "🍝", image: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["120g Vollkornpasta", "200g Hackfleisch", "1 Dose Tomaten", "1 Zwiebel", "1 Karotte", "Kräuter"],
    steps: ["Zwiebel und Karotte würfeln, mit dem Hack anbraten.", "Tomaten und Kräuter zugeben, 15 Minuten köcheln lassen.", "Pasta nach Packung al dente kochen.", "Sauce über die Pasta geben und servieren."] },
  { id: "p-airfryer-garnelen", name: "Airfryer Garnelen", category: "main", prep_min: 12, kcal: 240, prot: 34, carb: 4, fat: 9, equipment: ["airfryer"], icon: "🦐", image: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Garnelen", "1 Knoblauchzehe", "1 EL Olivenöl", "1/2 Zitrone", "Petersilie", "Salz"],
    steps: ["Garnelen mit Öl, gepresstem Knoblauch und Salz marinieren.", "Airfryer auf 200 °C vorheizen.", "6–7 Minuten garen, bis sie rosa sind.", "Mit Zitrone und Petersilie servieren."] },
  { id: "p-linsen-dal", name: "Linsen-Dal", category: "main", prep_min: 25, kcal: 420, prot: 24, carb: 58, fat: 8, equipment: ["stove"], icon: "🍛", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g rote Linsen", "1 Dose Kokosmilch light", "1 Zwiebel", "1 TL Curry", "1 Stück Ingwer", "Spinat"],
    steps: ["Zwiebel und Ingwer anbraten, Curry kurz mitrösten.", "Linsen und Kokosmilch zugeben, 15 Minuten köcheln.", "Bei Bedarf Wasser nachgießen, bis das Dal cremig ist.", "Spinat unterheben und servieren."] },
  { id: "p-reiskocher-huehnerreis", name: "Reiskocher Hühnerreis", category: "main", prep_min: 30, kcal: 500, prot: 34, carb: 62, fat: 10, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Reis", "200g Hähnchen", "500ml Brühe", "1 Karotte", "Erbsen", "Sojasauce"],
    steps: ["Hähnchen und Karotte würfeln.", "Alles mit Reis, Erbsen und Brühe in den Reiskocher geben.", "Auf 'Cook' stellen und 25 Minuten garen.", "Mit Sojasauce abschmecken und auflockern."] },
  { id: "p-airfryer-gemuese-frittata", name: "Airfryer Gemüse-Frittata", category: "main", prep_min: 20, kcal: 320, prot: 24, carb: 12, fat: 20, equipment: ["airfryer"], icon: "🍳", image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["4 Eier", "1 Paprika", "1 Zucchini", "50g Feta", "Salz, Pfeffer"],
    steps: ["Gemüse fein würfeln und in eine ofenfeste Form geben.", "Eier verquirlen, würzen und darübergießen, Feta zerbröseln.", "Airfryer auf 170 °C, Form einsetzen.", "15 Minuten backen, bis die Frittata gestockt ist."] },
  { id: "p-thunfisch-wrap", name: "Thunfisch-Wrap", category: "main", prep_min: 8, kcal: 400, prot: 32, carb: 40, fat: 12, equipment: ["none"], icon: "🌯", image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Vollkorn-Wrap", "1 Dose Thunfisch", "2 EL Skyr", "Salat, Tomate", "Mais", "Salz, Pfeffer"],
    steps: ["Thunfisch abtropfen und mit Skyr und Gewürzen vermengen.", "Wrap mit Salatblättern belegen.", "Thunfischcreme, Tomate und Mais daraufgeben.", "Fest einrollen und halbieren."] },
  { id: "p-airfryer-tofu-bowl", name: "Airfryer Tofu-Bowl", category: "main", prep_min: 20, kcal: 420, prot: 26, carb: 44, fat: 16, equipment: ["airfryer"], icon: "🍱", image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Tofu", "150g Reis", "2 EL Sojasauce", "1 TL Sesam", "Edamame", "Frühlingszwiebel"],
    steps: ["Tofu würfeln, in Sojasauce marinieren.", "Airfryer auf 200 °C, Tofu 14 Minuten knusprig backen, einmal schütteln.", "Reis kochen und in eine Bowl geben.", "Mit Tofu, Edamame, Sesam und Frühlingszwiebel anrichten."] },
  { id: "p-haehnchen-gemuese-pfanne", name: "Hähnchen-Gemüse-Pfanne", category: "main", prep_min: 20, kcal: 430, prot: 40, carb: 26, fat: 16, equipment: ["stove"], icon: "🍲", image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g Hähnchen", "1 Brokkoli", "1 Paprika", "2 EL Sojasauce", "1 EL Öl", "Sesam"],
    steps: ["Hähnchen würfeln und scharf anbraten.", "Gemüse zugeben und 5–6 Minuten mitbraten.", "Mit Sojasauce ablöschen und mit Sesam bestreuen."] },
  { id: "p-airfryer-putenschnitzel", name: "Airfryer Putenschnitzel", category: "main", prep_min: 18, kcal: 390, prot: 44, carb: 20, fat: 12, equipment: ["airfryer"], icon: "🍗", image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Putenschnitzel", "1 Ei", "Vollkorn-Semmelbrösel", "1 TL Paprika", "Salz, Pfeffer"],
    steps: ["Schnitzel würzen, in Ei und dann in Semmelbröseln panieren.", "Panade leicht andrücken und mit Öl besprühen.", "Airfryer auf 190 °C, 12 Minuten backen, einmal wenden.", "Mit Zitrone servieren."] },
  { id: "p-reiskocher-chili-con-carne", name: "Reiskocher Chili con Carne", category: "main", prep_min: 40, kcal: 520, prot: 34, carb: 58, fat: 16, equipment: ["ricecooker"], icon: "🌶️", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Hackfleisch", "1 Dose Kidneybohnen", "1 Dose Tomaten", "1 Zwiebel", "150g Reis", "Chili, Kreuzkümmel"],
    steps: ["Hack, Zwiebel, Bohnen, Tomaten und Gewürze in den Reiskocher geben.", "Reis und 300ml Wasser zufügen.", "Auf 'Cook' stellen und 30 Minuten garen, einmal umrühren.", "Vor dem Servieren 5 Minuten ruhen lassen."] },
  { id: "p-airfryer-lachsburger", name: "Airfryer Lachsburger", category: "main", prep_min: 20, kcal: 480, prot: 36, carb: 34, fat: 20, equipment: ["airfryer"], icon: "🍔", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Lachs", "1 Vollkornbrötchen", "1 Ei", "2 EL Haferflocken", "Salat, Joghurtsauce"],
    steps: ["Lachs fein hacken und mit Ei und Haferflocken zu einer Masse mischen.", "Zwei Patties formen.", "Airfryer auf 190 °C, 12 Minuten backen, einmal wenden.", "Brötchen mit Salat, Patty und Joghurtsauce füllen."] },
  { id: "p-ofen-gemuese-mit-feta-airfryer", name: "Ofen-Gemüse mit Feta (Airfryer)", category: "main", prep_min: 22, kcal: 360, prot: 16, carb: 34, fat: 18, equipment: ["airfryer"], icon: "🧀", image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Zucchini", "1 Paprika", "1 rote Zwiebel", "100g Feta", "1 EL Olivenöl", "Oregano"],
    steps: ["Gemüse in mundgerechte Stücke schneiden, mit Öl und Oregano mischen.", "Airfryer auf 190 °C, 12 Minuten rösten, einmal schütteln.", "Feta zerbröseln, darüberstreuen und 3 Minuten weitergaren.", "Warm servieren."] },
  { id: "p-reiskocher-dampf-fisch", name: "Reiskocher Dampf-Fisch", category: "main", prep_min: 25, kcal: 300, prot: 34, carb: 8, fat: 14, equipment: ["ricecooker"], icon: "🐟", image: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Weißfisch", "1 Stück Ingwer", "2 EL Sojasauce", "Frühlingszwiebel", "150g Reis"],
    steps: ["Reis mit Wasser in den Reiskocher geben.", "Fisch mit Ingwer und Sojasauce in ein Dampfsieb legen.", "Sieb einsetzen und alles zusammen 20 Minuten garen.", "Mit Frühlingszwiebel bestreuen."] },
  { id: "p-airfryer-haehnchen-nuggets", name: "Airfryer Hähnchen-Nuggets", category: "main", prep_min: 18, kcal: 360, prot: 38, carb: 24, fat: 12, equipment: ["airfryer"], icon: "🍗", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g Hähnchenbrust", "1 Ei", "Vollkorn-Semmelbrösel", "1 TL Paprika", "Salz"],
    steps: ["Hähnchen in mundgerechte Stücke schneiden, würzen.", "In Ei und dann in Semmelbröseln wenden.", "Airfryer auf 200 °C, 12 Minuten backen, einmal schütteln.", "Mit selbstgemachtem Joghurt-Dip servieren."] },
  { id: "p-quinoa-power-bowl", name: "Quinoa-Power-Bowl", category: "main", prep_min: 20, kcal: 450, prot: 22, carb: 56, fat: 16, equipment: ["stove"], icon: "🥗", image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["100g Quinoa", "1 Dose Kichererbsen", "1/2 Avocado", "Cherrytomaten", "Zitrone-Tahini-Dressing"],
    steps: ["Quinoa nach Packung 15 Minuten garen.", "Kichererbsen abspülen, Gemüse schneiden.", "Alles in einer Bowl anrichten.", "Mit Zitrone-Tahini-Dressing beträufeln."] },
  { id: "p-airfryer-pizza-toast", name: "Airfryer Pizza-Toast", category: "main", prep_min: 12, kcal: 380, prot: 22, carb: 40, fat: 14, equipment: ["airfryer"], icon: "🍕", image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Scheiben Vollkornbrot", "3 EL Tomatensauce", "60g Mozzarella", "Putenschinken", "Oregano"],
    steps: ["Brot mit Tomatensauce bestreichen.", "Mit Putenschinken und Mozzarella belegen.", "Airfryer auf 180 °C, 7 Minuten backen bis der Käse schmilzt.", "Mit Oregano bestreuen."] },
  { id: "p-rindersteak-ofenkartoffel", name: "Rindersteak & Ofenkartoffel", category: "main", prep_min: 25, kcal: 560, prot: 46, carb: 40, fat: 22, equipment: ["stove"], icon: "🥩", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Rindersteak", "2 Kartoffeln", "1 EL Butter", "Rosmarin", "Salz, Pfeffer"],
    steps: ["Kartoffeln vierteln und im Airfryer bei 200 °C 20 Min. garen.", "Steak salzen und in heißer Pfanne pro Seite 3 Minuten braten.", "Butter und Rosmarin zugeben, das Steak damit übergießen.", "5 Minuten ruhen lassen, dann mit den Kartoffeln servieren."] },
  { id: "p-reiskocher-kokos-curry", name: "Reiskocher Kokos-Curry", category: "main", prep_min: 30, kcal: 500, prot: 26, carb: 60, fat: 16, equipment: ["ricecooker"], icon: "🍛", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Hähnchen", "1 Dose Kokosmilch", "150g Reis", "1 Paprika", "2 EL rote Currypaste"],
    steps: ["Hähnchen und Paprika würfeln.", "Mit Currypaste, Kokosmilch und Reis in den Reiskocher geben.", "200ml Wasser zufügen und auf 'Cook' stellen.", "25 Minuten garen und vor dem Servieren umrühren."] },
  { id: "p-airfryer-auberginen-roellchen", name: "Airfryer Auberginen-Röllchen", category: "main", prep_min: 25, kcal: 340, prot: 20, carb: 22, fat: 18, equipment: ["airfryer"], icon: "🍆", image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Aubergine", "150g Ricotta", "2 EL Tomatensauce", "30g Parmesan", "Basilikum"],
    steps: ["Aubergine längs in dünne Scheiben schneiden und mit Öl bepinseln.", "Airfryer auf 180 °C, Scheiben 6 Minuten vorgaren.", "Ricotta auf die Scheiben streichen, aufrollen, in Tomatensauce setzen.", "Mit Parmesan bestreuen und 8 Minuten überbacken."] },
  { id: "p-haehnchen-caesar-salat", name: "Hähnchen-Caesar-Salat", category: "main", prep_min: 18, kcal: 420, prot: 40, carb: 18, fat: 22, equipment: ["stove"], icon: "🥗", image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Hähnchen", "Römersalat", "30g Parmesan", "2 EL Joghurt-Caesar-Dressing", "Vollkorn-Croutons"],
    steps: ["Hähnchen würzen und in der Pfanne goldbraun braten, dann in Streifen schneiden.", "Salat waschen und in eine Schüssel geben.", "Mit Dressing vermengen, Hähnchen, Croutons und Parmesan darüber."] },
  { id: "p-reiskocher-linsen-eintopf", name: "Reiskocher Linsen-Eintopf", category: "main", prep_min: 40, kcal: 440, prot: 26, carb: 60, fat: 8, equipment: ["ricecooker"], icon: "🍲", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g Linsen", "1 Karotte", "1 Kartoffel", "1 Zwiebel", "750ml Brühe", "Kräuter"],
    steps: ["Gemüse würfeln und mit den Linsen in den Reiskocher geben.", "Brühe und Kräuter zufügen.", "Auf 'Cook' stellen und 35 Minuten garen.", "Abschmecken und heiß servieren."] },
  { id: "p-airfryer-blumenkohl-wings", name: "Airfryer Blumenkohl-Wings", category: "main", prep_min: 22, kcal: 300, prot: 12, carb: 40, fat: 10, equipment: ["airfryer"], icon: "🥦", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Blumenkohl", "60g Mehl", "100ml Milch", "3 EL Buffalosauce", "1 TL Paprika"],
    steps: ["Blumenkohl in Röschen teilen.", "Mehl, Milch und Paprika zu einem Teig rühren, Röschen darin wenden.", "Airfryer auf 200 °C, 14 Minuten backen, einmal schütteln.", "Mit Buffalosauce bestreichen und 3 Minuten weitergaren."] },
  { id: "p-truthahn-reis-bowl", name: "Truthahn-Reis-Bowl", category: "main", prep_min: 30, kcal: 480, prot: 42, carb: 54, fat: 10, equipment: ["ricecooker"], icon: "🦃", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Putenhack", "150g Reis", "1 Zucchini", "2 EL Teriyaki", "Sesam"],
    steps: ["Reis im Reiskocher garen.", "Putenhack mit Zucchini in der Pfanne anbraten.", "Mit Teriyaki ablöschen.", "Über den Reis geben und mit Sesam bestreuen."] },
  { id: "p-airfryer-schweinefilet", name: "Airfryer Schweinefilet", category: "main", prep_min: 25, kcal: 420, prot: 46, carb: 6, fat: 22, equipment: ["airfryer"], icon: "🥩", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g Schweinefilet", "1 TL Senf", "1 TL Honig", "Rosmarin", "Salz, Pfeffer"],
    steps: ["Filet mit Senf, Honig und Gewürzen einreiben.", "Airfryer auf 190 °C vorheizen.", "18 Minuten garen, nach der Hälfte wenden.", "In Alufolie 5 Minuten ruhen lassen, dann in Medaillons schneiden."] },
  { id: "p-gemuese-omelette", name: "Gemüse-Omelette", category: "main", prep_min: 12, kcal: 320, prot: 26, carb: 8, fat: 20, equipment: ["stove"], icon: "🍳", image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 Eier", "1 Handvoll Champignons", "1/2 Paprika", "30g Käse", "Schnittlauch"],
    steps: ["Gemüse würfeln und in der Pfanne anbraten.", "Eier verquirlen, würzen und über das Gemüse gießen.", "Bei kleiner Hitze stocken lassen, Käse darüber.", "Zusammenklappen und servieren."] },
  { id: "p-reiskocher-erbsen-reis-mit-ei", name: "Reiskocher Erbsen-Reis mit Ei", category: "main", prep_min: 25, kcal: 440, prot: 20, carb: 66, fat: 12, equipment: ["ricecooker"], icon: "🍚", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Reis", "100g Erbsen", "2 Eier", "2 EL Sojasauce", "Frühlingszwiebel"],
    steps: ["Reis und Erbsen mit Wasser in den Reiskocher geben und garen.", "Eier in einer Pfanne zu Rührei braten.", "Rührei und Sojasauce unter den fertigen Reis heben.", "Mit Frühlingszwiebeln bestreuen."] },
  { id: "p-airfryer-haehnchen-teriyaki", name: "Airfryer Hähnchen Teriyaki", category: "main", prep_min: 20, kcal: 420, prot: 42, carb: 30, fat: 12, equipment: ["airfryer"], icon: "🍗", image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g Hähnchen", "3 EL Teriyaki", "1 TL Sesam", "150g Reis", "Brokkoli"],
    steps: ["Hähnchen in Teriyaki 15 Minuten marinieren.", "Airfryer auf 200 °C, Hähnchen 14 Minuten garen, einmal wenden.", "Reis und Brokkoli separat garen.", "Alles anrichten und mit Sesam bestreuen."] },
  { id: "p-kichererbsen-shakshuka", name: "Kichererbsen-Shakshuka", category: "main", prep_min: 22, kcal: 400, prot: 22, carb: 40, fat: 16, equipment: ["stove"], icon: "🍳", image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Dose Kichererbsen", "1 Dose Tomaten", "3 Eier", "1 Zwiebel", "1 TL Kreuzkümmel", "Feta"],
    steps: ["Zwiebel anbraten, Kichererbsen und Tomaten mit Kreuzkümmel zugeben.", "10 Minuten köcheln lassen.", "Mulden formen, Eier hineingeben, zugedeckt garen.", "Mit Feta bestreuen und servieren."] },
  { id: "p-reiskocher-butter-chicken", name: "Reiskocher Butter Chicken", category: "main", prep_min: 35, kcal: 540, prot: 34, carb: 52, fat: 20, equipment: ["ricecooker"], icon: "🍛", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Hähnchen", "150g Tomatenmark", "100ml Sahne", "1 TL Garam Masala", "150g Reis", "1 EL Butter"],
    steps: ["Hähnchen würfeln.", "Mit Tomatenmark, Gewürzen, Butter und 300ml Wasser in den Reiskocher geben.", "Auf 'Cook' stellen, nach 20 Min. Sahne einrühren.", "Mit separat gekochtem Reis servieren."] },
  { id: "p-airfryer-zucchini-puffer", name: "Airfryer Zucchini-Puffer", category: "main", prep_min: 20, kcal: 300, prot: 16, carb: 26, fat: 14, equipment: ["airfryer"], icon: "🥬", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Zucchini", "2 Eier", "40g Mehl", "30g Parmesan", "Salz, Pfeffer"],
    steps: ["Zucchini raspeln, salzen und gut ausdrücken.", "Mit Eiern, Mehl und Parmesan zu einer Masse mischen.", "Kleine Puffer formen und mit Öl bepinseln.", "Airfryer auf 190 °C, 12 Minuten backen, einmal wenden."] },
  { id: "p-rind-reis-pfanne", name: "Rind-Reis-Pfanne", category: "main", prep_min: 22, kcal: 520, prot: 40, carb: 50, fat: 16, equipment: ["stove"], icon: "🍲", image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Rinderstreifen", "150g Reis", "1 Paprika", "2 EL Austernsauce", "Frühlingszwiebel"],
    steps: ["Reis vorkochen.", "Rind scharf anbraten, herausnehmen.", "Paprika anbraten, Reis und Rind zugeben.", "Mit Austernsauce ablöschen und mit Frühlingszwiebel bestreuen."] },
  { id: "p-airfryer-protein-brownie", name: "Airfryer Protein-Brownie", category: "dessert", prep_min: 20, kcal: 240, prot: 18, carb: 24, fat: 8, equipment: ["airfryer"], icon: "🍫", image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Scoop Schoko-Protein", "1 Ei", "30g Haferflocken", "1 EL Kakao", "Süßstoff"],
    steps: ["Alle Zutaten zu einem glatten Teig verrühren.", "In eine kleine gefettete Auflaufform füllen.", "Airfryer auf 170 °C, 12 Minuten backen.", "Leicht abkühlen lassen – innen bleibt er fudgy."] },
  { id: "p-skyr-eiscreme", name: "Skyr-Eiscreme", category: "dessert", prep_min: 10, kcal: 180, prot: 22, carb: 18, fat: 2, equipment: ["none"], icon: "🍨", image: "https://images.unsplash.com/photo-1559054663-e8d23213f55c?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g Skyr", "1 gefrorene Banane", "1 TL Vanille", "Süßstoff"],
    steps: ["Gefrorene Banane mit Skyr und Vanille cremig mixen.", "In eine Form füllen und 1 Stunde ins Gefrierfach stellen.", "Kurz antauen lassen und cremig löffeln."] },
  { id: "p-protein-mug-cake", name: "Protein-Mug-Cake", category: "dessert", prep_min: 5, kcal: 260, prot: 24, carb: 24, fat: 8, equipment: ["none"], icon: "🍰", image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Scoop Protein", "1 Ei", "20g Haferflocken", "1 TL Kakao", "1/2 TL Backpulver"],
    steps: ["Alle Zutaten direkt in einer großen Tasse verrühren.", "In der Mikrowelle bei 800 W 90 Sekunden backen.", "Kurz abkühlen lassen und direkt aus der Tasse löffeln."] },
  { id: "p-airfryer-bratapfel", name: "Airfryer Bratapfel", category: "dessert", prep_min: 20, kcal: 210, prot: 4, carb: 40, fat: 5, equipment: ["airfryer"], icon: "🍎", image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Äpfel", "20g Nüsse", "1 TL Honig", "1 TL Zimt", "Rosinen"],
    steps: ["Äpfel entkernen und eine Mulde ausstechen.", "Nüsse, Rosinen, Honig und Zimt mischen und einfüllen.", "Airfryer auf 170 °C, 15 Minuten backen.", "Warm servieren, optional mit Skyr."] },
  { id: "p-beeren-nicecream", name: "Beeren-Nicecream", category: "dessert", prep_min: 8, kcal: 190, prot: 6, carb: 38, fat: 3, equipment: ["none"], icon: "🍧", image: "https://images.unsplash.com/photo-1559054663-e8d23213f55c?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 gefrorene Bananen", "100g TK-Beeren", "2 EL Milch"],
    steps: ["Gefrorene Bananen und Beeren mit etwas Milch mixen.", "So lange pürieren, bis eine cremige Softeis-Konsistenz entsteht.", "Sofort servieren oder kurz anfrieren."] },
  { id: "p-reiskocher-schoko-kuchen", name: "Reiskocher Schoko-Kuchen", category: "dessert", prep_min: 45, kcal: 320, prot: 12, carb: 44, fat: 12, equipment: ["ricecooker"], icon: "🎂", image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g Mehl", "2 Eier", "3 EL Kakao", "80g Zucker", "100ml Milch", "1 TL Backpulver"],
    steps: ["Alle Zutaten zu einem glatten Teig verrühren.", "Reiskocher-Topf einfetten und den Teig einfüllen.", "Auf 'Cook' stellen; schaltet er ab, erneut starten (insgesamt ~40 Min.).", "Mit einem Stäbchen testen und gestürzt servieren."] },
  { id: "p-protein-cheesecake-im-glas", name: "Protein-Cheesecake im Glas", category: "dessert", prep_min: 10, kcal: 280, prot: 30, carb: 24, fat: 6, equipment: ["none"], icon: "🍮", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Magerquark", "1 Scoop Vanille-Protein", "4 Butterkekse", "100g Beeren", "Süßstoff"],
    steps: ["Kekse zerbröseln und in ein Glas geben.", "Quark mit Protein und Süßstoff cremig rühren.", "Auf die Kekse schichten und mit Beeren toppen.", "30 Minuten kühl stellen."] },
  { id: "p-airfryer-protein-cookies", name: "Airfryer Protein-Cookies", category: "dessert", prep_min: 15, kcal: 220, prot: 14, carb: 22, fat: 9, equipment: ["airfryer"], icon: "🍪", image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["40g Haferflocken", "1 Scoop Protein", "1 Banane", "1 EL Erdnussbutter", "Schokostückchen"],
    steps: ["Banane zerdrücken und mit allen Zutaten vermengen.", "Kleine Cookies formen und auf Backpapier setzen.", "Airfryer auf 170 °C, 8–10 Minuten backen.", "Auskühlen lassen, damit sie fest werden."] },
  { id: "p-chia-schoko-pudding", name: "Chia-Schoko-Pudding", category: "dessert", prep_min: 5, kcal: 260, prot: 14, carb: 28, fat: 12, equipment: ["none"], icon: "🍫", image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["3 EL Chiasamen", "250ml Milch", "1 EL Kakao", "1 TL Honig", "Banane"],
    steps: ["Chiasamen, Milch, Kakao und Honig verrühren.", "10 Minuten quellen lassen, dann erneut umrühren.", "Über Nacht kühlen.", "Mit Bananenscheiben servieren."] },
  { id: "p-quark-beeren-auflauf-airfryer", name: "Quark-Beeren-Auflauf (Airfryer)", category: "dessert", prep_min: 22, kcal: 250, prot: 26, carb: 24, fat: 5, equipment: ["airfryer"], icon: "🫐", image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Magerquark", "2 Eier", "20g Grieß", "100g Beeren", "Süßstoff"],
    steps: ["Quark, Eier, Grieß und Süßstoff verrühren.", "Beeren unterheben und in eine kleine Form füllen.", "Airfryer auf 170 °C, 16 Minuten backen.", "Warm oder kalt genießen."] },
  { id: "p-bananenbrot-muffins-airfryer", name: "Bananenbrot-Muffins (Airfryer)", category: "dessert", prep_min: 22, kcal: 230, prot: 10, carb: 34, fat: 7, equipment: ["airfryer"], icon: "🍌", image: "https://images.unsplash.com/photo-1613145997970-db84a7975fbb?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Bananen", "2 Eier", "80g Haferflocken", "1 Scoop Protein", "1 TL Backpulver"],
    steps: ["Bananen zerdrücken, alle Zutaten zu einem Teig verrühren.", "In Silikon-Muffinförmchen füllen.", "Airfryer auf 160 °C, 15 Minuten backen.", "Stäbchenprobe machen und auskühlen lassen."] },
  { id: "p-kokos-reis-pudding", name: "Kokos-Reis-Pudding", category: "dessert", prep_min: 35, kcal: 340, prot: 8, carb: 58, fat: 10, equipment: ["ricecooker"], icon: "🥥", image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["100g Milchreis", "400ml Kokosmilch light", "1 EL Zucker", "Mango", "Kokoschips"],
    steps: ["Milchreis mit Kokosmilch und Zucker in den Reiskocher geben.", "Auf 'Cook' stellen, gelegentlich rühren.", "Nach 25 Minuten cremig quellen lassen.", "Mit Mango und Kokoschips servieren."] },
  { id: "p-erdnussbutter-energy-fudge", name: "Erdnussbutter-Energy-Fudge", category: "dessert", prep_min: 10, kcal: 210, prot: 10, carb: 16, fat: 12, equipment: ["none"], icon: "🥜", image: "https://images.unsplash.com/photo-1604909052743-94e838986d24?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["100g Erdnussbutter", "2 EL Honig", "1 Scoop Protein", "30g Haferflocken", "Dunkle Schokolade"],
    steps: ["Erdnussbutter, Honig, Protein und Haferflocken verkneten.", "In eine kleine Form drücken und mit geschmolzener Schokolade übergießen.", "1 Stunde kühlen und in Würfel schneiden."] },
  { id: "p-airfryer-zimtschnecken", name: "Airfryer Zimtschnecken", category: "dessert", prep_min: 25, kcal: 290, prot: 8, carb: 48, fat: 8, equipment: ["airfryer"], icon: "🌀", image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Rolle Vollkorn-Blätterteig", "1 EL Butter", "2 EL Zucker", "1 TL Zimt", "Frischkäse-Glasur"],
    steps: ["Teig ausrollen, mit Butter bestreichen, Zucker und Zimt bestreuen.", "Aufrollen und in Scheiben schneiden.", "Airfryer auf 170 °C, 10 Minuten backen.", "Mit Frischkäse-Glasur bestreichen."] },
  { id: "p-protein-tiramisu", name: "Protein-Tiramisu", category: "dessert", prep_min: 15, kcal: 300, prot: 28, carb: 26, fat: 8, equipment: ["none"], icon: "☕", image: "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Magerquark", "1 Scoop Vanille-Protein", "4 Löffelbiskuits", "1 Tasse Espresso", "Kakao"],
    steps: ["Quark mit Protein cremig rühren.", "Löffelbiskuits kurz in Espresso tauchen und in ein Glas legen.", "Mit der Quarkcreme bedecken und schichten.", "Mit Kakao bestäuben und 1 Stunde kühlen."] },
  { id: "p-gebackene-banane-airfryer", name: "Gebackene Banane (Airfryer)", category: "dessert", prep_min: 12, kcal: 200, prot: 5, carb: 42, fat: 3, equipment: ["airfryer"], icon: "🍌", image: "https://images.unsplash.com/photo-1613145997970-db84a7975fbb?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Bananen", "1 TL Honig", "1 TL Zimt", "10g gehackte Nüsse"],
    steps: ["Bananen längs einschneiden.", "Mit Honig beträufeln und mit Zimt und Nüssen bestreuen.", "Airfryer auf 180 °C, 8 Minuten backen.", "Warm servieren."] },
  { id: "p-joghurt-beeren-riegel-tk", name: "Joghurt-Beeren-Riegel (TK)", category: "dessert", prep_min: 10, kcal: 150, prot: 12, carb: 18, fat: 3, equipment: ["none"], icon: "🍦", image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["300g griechischer Joghurt", "100g Beeren", "1 EL Honig", "Granola"],
    steps: ["Joghurt mit Honig verrühren.", "Beeren und Granola unterheben.", "Auf ein Blech streichen und 3 Stunden gefrieren.", "In Riegel brechen und sofort essen."] },
  { id: "p-dattel-kakao-baellchen", name: "Dattel-Kakao-Bällchen", category: "dessert", prep_min: 12, kcal: 180, prot: 6, carb: 28, fat: 6, equipment: ["none"], icon: "🍫", image: "https://images.unsplash.com/photo-1604909052743-94e838986d24?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["8 Datteln", "30g Haferflocken", "1 EL Kakao", "20g Mandeln", "1 EL Wasser"],
    steps: ["Datteln und Mandeln fein hacken oder mixen.", "Haferflocken, Kakao und Wasser zugeben, zu einer Masse verkneten.", "Kleine Kugeln rollen.", "30 Minuten kühlen."] },
  { id: "p-airfryer-apfelchips", name: "Airfryer Apfelchips", category: "dessert", prep_min: 25, kcal: 120, prot: 1, carb: 30, fat: 0, equipment: ["airfryer"], icon: "🍏", image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Äpfel", "1 TL Zimt"],
    steps: ["Äpfel in hauchdünne Scheiben schneiden.", "Mit Zimt bestreuen.", "Airfryer auf 150 °C, 20 Minuten backen, mehrfach wenden.", "Auskühlen lassen – sie werden knusprig."] },
  { id: "p-protein-schoko-mousse", name: "Protein-Schoko-Mousse", category: "dessert", prep_min: 8, kcal: 240, prot: 26, carb: 20, fat: 6, equipment: ["none"], icon: "🍫", image: "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Magerquark", "1 Scoop Schoko-Protein", "100ml Milch", "1 EL Kakao", "Süßstoff"],
    steps: ["Quark, Protein, Milch und Kakao cremig aufschlagen.", "Süßstoff nach Geschmack zugeben.", "In Gläser füllen und 30 Minuten kühlen.", "Mit Beeren garnieren."] },
  { id: "p-airfryer-kichererbsen-snack", name: "Airfryer Kichererbsen-Snack", category: "snack", prep_min: 20, kcal: 190, prot: 10, carb: 26, fat: 6, equipment: ["airfryer"], icon: "🫛", image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Dose Kichererbsen", "1 EL Olivenöl", "1 TL Paprika", "1/2 TL Kreuzkümmel", "Salz"],
    steps: ["Kichererbsen abspülen und gut trocken tupfen.", "Mit Öl und Gewürzen vermengen.", "Airfryer auf 200 °C, 15 Minuten rösten, mehrmals schütteln.", "Auskühlen lassen – knusprig genießen."] },
  { id: "p-protein-shake-schoko", name: "Protein-Shake Schoko", category: "snack", prep_min: 3, kcal: 220, prot: 30, carb: 18, fat: 4, equipment: ["none"], icon: "🥤", image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Scoop Schoko-Protein", "300ml Milch", "1/2 Banane", "Eiswürfel"],
    steps: ["Alle Zutaten in einen Shaker oder Mixer geben.", "30 Sekunden kräftig mixen.", "Über Eiswürfel gießen und sofort trinken."] },
  { id: "p-quark-dip-mit-gemuese", name: "Quark-Dip mit Gemüse", category: "snack", prep_min: 8, kcal: 160, prot: 20, carb: 12, fat: 4, equipment: ["none"], icon: "🥕", image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Magerquark", "Schnittlauch", "1 Karotte", "1 Gurke", "1 Paprika", "Salz, Pfeffer"],
    steps: ["Quark mit Schnittlauch, Salz und Pfeffer verrühren.", "Gemüse in Sticks schneiden.", "Zum Dippen servieren."] },
  { id: "p-airfryer-edamame", name: "Airfryer Edamame", category: "snack", prep_min: 12, kcal: 180, prot: 16, carb: 14, fat: 8, equipment: ["airfryer"], icon: "🫛", image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Edamame (TK)", "1 TL Sesamöl", "Meersalz", "Chiliflocken"],
    steps: ["Edamame mit Sesamöl vermengen.", "Airfryer auf 190 °C, 8 Minuten garen, einmal schütteln.", "Mit Meersalz und Chiliflocken bestreuen."] },
  { id: "p-reiskocher-edamame-reis", name: "Reiskocher Edamame-Reis", category: "snack", prep_min: 25, kcal: 320, prot: 12, carb: 58, fat: 6, equipment: ["ricecooker"], icon: "🍙", image: "https://images.unsplash.com/photo-1517093157656-b9eccef91cb1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g Reis", "100g Edamame", "1 TL Sesam", "1 EL Sojasauce", "Nori"],
    steps: ["Reis und Edamame mit Wasser in den Reiskocher geben.", "Auf 'Cook' stellen und 20 Minuten garen.", "Mit Sojasauce und Sesam mischen.", "In kleine Onigiri formen und mit Nori umwickeln."] },
  { id: "p-skyr-mit-nuessen-honig", name: "Skyr mit Nüssen & Honig", category: "snack", prep_min: 4, kcal: 250, prot: 26, carb: 20, fat: 8, equipment: ["none"], icon: "🍯", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Skyr", "20g Walnüsse", "1 TL Honig", "Zimt"],
    steps: ["Skyr in eine Schale geben.", "Mit Nüssen, Honig und Zimt toppen.", "Sofort löffeln."] },
  { id: "p-airfryer-kaese-chips", name: "Airfryer Käse-Chips", category: "snack", prep_min: 10, kcal: 200, prot: 18, carb: 2, fat: 15, equipment: ["airfryer"], icon: "🧀", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["80g geriebener Käse", "Paprikapulver"],
    steps: ["Kleine Käsehäufchen auf Backpapier setzen, flach drücken.", "Mit Paprika bestreuen.", "Airfryer auf 180 °C, 5–6 Minuten backen, bis knusprig.", "Auskühlen lassen – sie werden fest."] },
  { id: "p-erdnussbutter-apfel", name: "Erdnussbutter-Apfel", category: "snack", prep_min: 3, kcal: 210, prot: 8, carb: 26, fat: 10, equipment: ["none"], icon: "🍎", image: "https://images.unsplash.com/photo-1613145997970-db84a7975fbb?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Apfel", "1 EL Erdnussbutter", "1 TL Haferflocken"],
    steps: ["Apfel in Scheiben schneiden.", "Mit Erdnussbutter bestreichen.", "Mit Haferflocken bestreuen und genießen."] },
  { id: "p-reiscracker-mit-skyr-thunfisch", name: "Reiscracker mit Skyr-Thunfisch", category: "snack", prep_min: 6, kcal: 180, prot: 22, carb: 18, fat: 4, equipment: ["none"], icon: "🍘", image: "https://images.unsplash.com/photo-1517093157656-b9eccef91cb1?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["4 Reiscracker", "1 Dose Thunfisch", "2 EL Skyr", "Schnittlauch", "Pfeffer"],
    steps: ["Thunfisch mit Skyr und Schnittlauch vermengen.", "Auf die Reiscracker verteilen.", "Mit Pfeffer würzen."] },
  { id: "p-protein-riegel-selbstgemacht", name: "Protein-Riegel selbstgemacht", category: "snack", prep_min: 15, kcal: 230, prot: 18, carb: 22, fat: 8, equipment: ["none"], icon: "🍫", image: "https://images.unsplash.com/photo-1604909052743-94e838986d24?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Scoops Protein", "60g Haferflocken", "2 EL Erdnussbutter", "3 EL Milch", "Schokolade"],
    steps: ["Protein, Haferflocken, Erdnussbutter und Milch verkneten.", "In eine Form drücken und glatt streichen.", "Mit geschmolzener Schokolade überziehen.", "1 Stunde kühlen und in Riegel schneiden."] },
  { id: "p-airfryer-suesskartoffel-chips", name: "Airfryer Süßkartoffel-Chips", category: "snack", prep_min: 20, kcal: 160, prot: 3, carb: 32, fat: 4, equipment: ["airfryer"], icon: "🍠", image: "https://images.unsplash.com/photo-1493770348161-369560ae357d?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Süßkartoffel", "1 TL Olivenöl", "Salz", "Paprika"],
    steps: ["Süßkartoffel in hauchdünne Scheiben hobeln.", "Mit Öl, Salz und Paprika vermengen.", "Airfryer auf 170 °C, 15 Minuten backen, mehrfach wenden.", "Auskühlen lassen bis knusprig."] },
  { id: "p-bananen-protein-muffins-to-go", name: "Bananen-Protein-Muffins to go", category: "snack", prep_min: 20, kcal: 200, prot: 12, carb: 26, fat: 6, equipment: ["airfryer"], icon: "🧁", image: "https://images.unsplash.com/photo-1613145997970-db84a7975fbb?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["2 Bananen", "1 Ei", "60g Haferflocken", "1 Scoop Protein", "1 TL Backpulver"],
    steps: ["Bananen zerdrücken, alle Zutaten verrühren.", "In Förmchen füllen.", "Airfryer auf 160 °C, 14 Minuten backen.", "Auskühlen lassen und mitnehmen."] },
  { id: "p-griechischer-joghurt-dip", name: "Griechischer Joghurt-Dip", category: "snack", prep_min: 8, kcal: 170, prot: 14, carb: 10, fat: 8, equipment: ["none"], icon: "🥒", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g griechischer Joghurt", "1/2 Gurke", "1 Knoblauchzehe", "Dill", "Salz"],
    steps: ["Gurke raspeln und ausdrücken.", "Mit Joghurt, Knoblauch und Dill verrühren.", "Mit Salz abschmecken und kühl stellen."] },
  { id: "p-trail-mix-energie", name: "Trail-Mix Energie", category: "snack", prep_min: 5, kcal: 280, prot: 10, carb: 24, fat: 18, equipment: ["none"], icon: "🥜", image: "https://images.unsplash.com/photo-1467453678174-768ec283a940?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["30g Mandeln", "20g Cashews", "20g Rosinen", "10g dunkle Schokolade", "Kürbiskerne"],
    steps: ["Alle Zutaten abwiegen.", "In einer Schüssel vermengen.", "In eine Dose füllen – ideal für unterwegs."] },
  { id: "p-airfryer-popcorn-haehnchen", name: "Airfryer Popcorn-Hähnchen", category: "snack", prep_min: 18, kcal: 300, prot: 34, carb: 16, fat: 10, equipment: ["airfryer"], icon: "🍗", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Hähnchen", "1 Ei", "Vollkorn-Semmelbrösel", "1 TL Paprika", "Salz"],
    steps: ["Hähnchen in kleine Würfel schneiden, würzen.", "In Ei und Semmelbröseln wenden.", "Airfryer auf 200 °C, 10 Minuten backen, einmal schütteln.", "Mit Dip servieren."] },
  { id: "p-mandel-dattel-riegel", name: "Mandel-Dattel-Riegel", category: "snack", prep_min: 12, kcal: 210, prot: 6, carb: 30, fat: 9, equipment: ["none"], icon: "🌰", image: "https://images.unsplash.com/photo-1604909052743-94e838986d24?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["10 Datteln", "40g Mandeln", "20g Haferflocken", "1 EL Kakaonibs"],
    steps: ["Datteln und Mandeln mixen, bis eine klebrige Masse entsteht.", "Haferflocken und Kakaonibs unterkneten.", "In eine Form pressen und kühlen.", "In Riegel schneiden."] },
  { id: "p-huettenkaese-bowl-herzhaft", name: "Hüttenkäse-Bowl herzhaft", category: "snack", prep_min: 5, kcal: 200, prot: 24, carb: 10, fat: 8, equipment: ["none"], icon: "🧀", image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["200g Hüttenkäse", "Cherrytomaten", "Gurke", "Schnittlauch", "Pfeffer"],
    steps: ["Hüttenkäse in eine Schale geben.", "Tomaten und Gurke würfeln, dazugeben.", "Mit Schnittlauch und Pfeffer würzen."] },
  { id: "p-airfryer-nuss-mix-geroestet", name: "Airfryer Nuss-Mix geröstet", category: "snack", prep_min: 12, kcal: 300, prot: 10, carb: 12, fat: 24, equipment: ["airfryer"], icon: "🥜", image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g gemischte Nüsse", "1 TL Honig", "1 TL Rosmarin", "Meersalz"],
    steps: ["Nüsse mit Honig, Rosmarin und Salz vermengen.", "Airfryer auf 160 °C, 8 Minuten rösten, einmal schütteln.", "Auskühlen lassen und luftdicht lagern."] },
  { id: "p-protein-smoothie-beere", name: "Protein-Smoothie Beere", category: "snack", prep_min: 4, kcal: 240, prot: 28, carb: 26, fat: 4, equipment: ["none"], icon: "🥤", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Scoop Vanille-Protein", "150g TK-Beeren", "250ml Milch", "1 TL Honig"],
    steps: ["Alle Zutaten in den Mixer geben.", "Cremig pürieren.", "In ein Glas gießen und sofort trinken."] },
  { id: "p-reiskocher-mais-bohnen-salat-warm", name: "Reiskocher Mais-Bohnen-Salat warm", category: "snack", prep_min: 20, kcal: 300, prot: 14, carb: 48, fat: 6, equipment: ["ricecooker"], icon: "🌽", image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["150g Reis", "1 Dose Mais", "1 Dose schwarze Bohnen", "Limette", "Koriander"],
    steps: ["Reis mit Wasser im Reiskocher garen.", "Mais und Bohnen abspülen und untermischen.", "Mit Limettensaft und Koriander abschmecken."] },
  { id: "p-gurken-feta-sticks", name: "Gurken-Feta-Sticks", category: "snack", prep_min: 6, kcal: 150, prot: 9, carb: 6, fat: 10, equipment: ["none"], icon: "🥒", image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["1 Gurke", "60g Feta", "Olivenöl", "Oregano"],
    steps: ["Gurke in Stangen schneiden.", "Feta würfeln und dazugeben.", "Mit Öl und Oregano beträufeln."] },
  { id: "p-airfryer-mozzarella-sticks", name: "Airfryer Mozzarella-Sticks", category: "snack", prep_min: 15, kcal: 280, prot: 20, carb: 20, fat: 14, equipment: ["airfryer"], icon: "🧀", image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["4 Mozzarella-Sticks", "1 Ei", "Vollkorn-Semmelbrösel", "1 TL Oregano"],
    steps: ["Mozzarella-Sticks in Ei und dann in Semmelbröseln panieren, kurz einfrieren.", "Nochmals panieren für eine dicke Kruste.", "Airfryer auf 190 °C, 7 Minuten backen.", "Sofort mit Tomatensauce servieren."] },
  { id: "p-overnight-protein-pudding", name: "Overnight-Protein-Pudding", category: "snack", prep_min: 5, kcal: 230, prot: 26, carb: 24, fat: 4, equipment: ["none"], icon: "🍮", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=640&q=70&auto=format&fit=crop", is_preset: true,
    ingredients: ["250g Magerquark", "1 Scoop Protein", "3 EL Haferflocken", "100ml Milch", "Beeren"],
    steps: ["Quark, Protein, Haferflocken und Milch verrühren.", "Über Nacht kühl stellen.", "Mit Beeren toppen und löffeln."] },
];
