/** Original visual modes. Theme ids remain stable so existing local settings migrate. */
export const THEMES: Record<string, any> = {
  shadow: {
    label: 'NIGHT',
    icon: '◈',
    title: 'CORELINE PROFILE',
    sigil: '◈ CORELINE',
    ranks: ['Starting line', 'Building rhythm', 'Consistent operator', 'Long-game athlete'],
    attrs: ['STR', 'REC', 'MOV', 'NUT', 'FOC'],
    xpLabel: 'CONSISTENCY',
    sleep2: { name: 'Recovery signal: high', desc: 'Recent sleep input suggests that a lighter day and earlier recovery routine may be useful.' },
    sleep1: { name: 'Recovery signal', desc: 'Recent sleep input suggests keeping intensity flexible today.' },
    alpha: { name: 'Routine logged', desc: 'Your selected morning routine is checked off for today.' },
    streak: { name: (n: number) => `${n}-day rhythm`, desc: 'You have recorded a complete day consistently.' },
    sugar: { name: 'Sugar target passed', desc: 'Today’s logged sugar is above your current planning target; review the entries in context.' },
  },
  system: {
    label: 'PULSE',
    icon: '↗',
    title: 'PULSE PROGRESS FILE',
    sigil: '↗ CORELINE PULSE',
    ranks: ['Baseline', 'Momentum', 'Strong rhythm', 'Peak consistency'],
    attrs: ['PWR', 'REC', 'MOV', 'FUEL', 'FOC'],
    xpLabel: 'MOMENTUM',
    sleep2: { name: 'Recovery load: high', desc: 'Recent sleep input supports reducing today’s effort and prioritizing recovery.' },
    sleep1: { name: 'Recovery load', desc: 'Keep today’s session adjustable and monitor how you feel.' },
    alpha: { name: 'Routine complete', desc: 'Your selected morning routine is logged.' },
    streak: { name: (n: number) => `${n}-day momentum`, desc: 'A consistent run of complete daily records.' },
    sugar: { name: 'Sugar target passed', desc: 'Logged sugar is above today’s planning target; inspect the meal context.' },
  },
  ghoul: {
    label: 'EMBER',
    icon: '◇',
    title: 'EMBER TRAINING FILE',
    sigil: '◇ CORELINE EMBER',
    ranks: ['Spark', 'Steady flame', 'Built habit', 'Durable engine'],
    attrs: ['STR', 'REC', 'MOV', 'FUEL', 'GRIT'],
    xpLabel: 'RHYTHM',
    sleep2: { name: 'Recovery reserve: low', desc: 'Recent sleep input supports a lighter day and a calmer recovery window.' },
    sleep1: { name: 'Recovery reserve', desc: 'Consider keeping today’s workload flexible.' },
    alpha: { name: 'Routine complete', desc: 'Your selected morning routine is logged.' },
    streak: { name: (n: number) => `${n}-day steady run`, desc: 'You have maintained a complete daily record.' },
    sugar: { name: 'Sugar target passed', desc: 'Logged sugar is above your current planning target; review without treating one day as a verdict.' },
  },
};
