// Auto-portiert: Theme-Konfiguration (Shadow / Solo Leveling / Tokyo Ghoul)
/* eslint-disable */
export const THEMES: Record<string, any> = {
  shadow: {
    label : 'SHADOW',
    icon  : '◈',
    title : 'SHADOW AGENT AKTE',
    sigil : '◈ SHADOW~1',
    ranks : ['Shadow Novice','Shadow Initiate','Seven Shadows Elite','Eminence in Shadow'],
    attrs : ['STR','VIT','AGI','INT','MAG'],
    xpLabel: 'XP',
    sleep2 : { name:'Schlafmangel Stufe II',       desc:'Dein physisches Gefäß zeigt Ermüdungserscheinungen. Regeneration um 25% verringert.'    },
    sleep1 : { name:'Schlafmangel Stufe I',        desc:'Leichte Regenerationseinbußen. Tiefschlafphasen fragmentiert. Magnesium empfohlen.'     },
    alpha  : { name:'Alpha-Erwachen aktiv',        desc:'Omega-3 & Multivitamin synchronisiert. +15% Fokus · Resonanz-Frequenz stabil.'         },
    streak : { name: n=>`Sieben-Schatten-Resonanz (${n}d)`, desc:'Kontinuierliche Protokoll-Adherenz registriert. Rang-Aura aktiv.'             },
    sugar  : { name:'Zucker-Kontamination',        desc:'Hohe Zuckerlast im Substrat detektiert. Kognitive Klarheit reduziert.'                 },
  },
  system: {
    label : 'SYSTEM',
    icon  : '⚡',
    title : 'HUNTER STATUS REPORT',
    sigil : '⚡ THE SYSTEM',
    ranks : ['E-Rank Hunter','D-Rank Hunter','A-Rank Hunter','Shadow Monarch'],
    attrs : ['STR','VIT','AGI','INT','MP'],
    xpLabel: 'DAILY QUEST',
    sleep2 : { name:'Erschöpfungs-Debuff II',      desc:'Hunter-Kondition kritisch. Quest-Performance −25%. Regeneration sofort einleiten.'      },
    sleep1 : { name:'Erschöpfungs-Debuff I',       desc:'Regenerationsrate eingeschränkt. Quest-Effizienz beeinträchtigt.'                       },
    alpha  : { name:'Daily Quest Bonus aktiv',     desc:'Basis-Supplemente bestätigt. +15% Quest-Effizienz · System-Synchronisation stabil.'    },
    streak : { name: n=>`Hunter Streak: ${n}d`,    desc:'Kontinuierliche Quest-Completion detektiert. Rang-Boost aktiv.'                        },
    sugar  : { name:'Mana-Vergiftung',             desc:'Übermäßige Zucker-Instabilität detektiert. Mana-Regeneration beeinträchtigt.'           },
  },
  ghoul: {
    label : 'CCG',
    icon  : '👁',
    title : 'SS-RATE GHOUL FILE',
    sigil : '👁 CCG DATABASE',
    ranks : ['Ghoul: Rank C','Ghoul: Rank B','Half-Ghoul','Kakuja'],
    attrs : ['STR','VIT','AGI','INT','RC'],
    xpLabel: 'THREAT LEVEL',
    sleep2 : { name:'Rc-Zellen-Instabilität II',   desc:'Ghoul-Organismus destabilisiert. Kagune-Kontrolle eingeschränkt. Kritischer Zustand.'   },
    sleep1 : { name:'Rc-Zellen-Instabilität I',    desc:'Leichte Rc-Zellen-Schwankungen. Kagune-Output reduziert. Ernährung stabilisieren.'      },
    alpha  : { name:'Nährstoff-Synchronisation',   desc:'Rc-Zellen stabilisiert. +15% Kagune-Resonanz · Quinque-Resistenz aktiv.'               },
    streak : { name: n=>`SS-Protokoll (${n}d)`,    desc:'Ghoul-Aktivität konstant erfasst. CCG-Ermittlungsakte wird aktualisiert.'               },
    sugar  : { name:'Kontaminierte Nahrungsquelle',desc:'Minderwertige Rc-Zellen-Zufuhr. Kagune-Aktivität destabilisiert.'                       },
  },
};
